865: Store SSA roles in the ApiClient object
SecureApiGateway/secure-api-gateway-ob-uk pull request #332
Opened 2023-03-06 10:56 UTC by BohoCode

Roles are needed for access decisions, and the roles in the SSA ultimately limit the roles that a client can request and the apis that a client can access. Each API request needs to know which roles were in the Software Statement and limit access accordingly.

Issue: https://github.com/secureapigateway/secureapigateway/issues/865

2023-03-06 17:21 UTC, jorgesanchezperez approved these changes

2023-03-06 17:28 UTC, merged

2023-03-06 17:31 UTC, dbadham-fr requested changes

2023-03-06 17:31 UTC, dbadham-fr commented on secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientService.java
> +    Logger log = LoggerFactory.getLogger(ApiClientService.class);
field is not used

2023-03-07 16:04 UTC, dbadham-fr commented on secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
> +                ", jwks=" + jwks.toJsonValue() +
Raised: https://github.com/SecureApiGateway/SecureApiGateway/issues/878

NPE has been observed in the logs.

2023-03-07 16:24 UTC, dbadham-fr commented on secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
> +                ", jwks=" + jwks.toJsonValue() +
Fixed: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/339